server:
  port:8761

eureka:
  instance:
    hostname: localhost
  client:
    #déclarer que c'est une serveur
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  server:
    enable-self-preservation: false


#server.port=8761
#eureka.client.fetch-registry=false
#eureka.client.register-with-eureka=false