server:
  port: 8771

# indiquer l'adresse de server
eureka:
  client:
    service-url:
      defautZone: http://localhost:8761/eureka/


# nommer le service
spring:
  application:
    name: orderService

#server.port=8081
#spring.application.name=client-service
#spring.datasource.url=jdbc:h2:mem:client-db
#spring.cloud.discovery.enabled=true
#management.endpoints.web.exposure.include=*
