server:
  port: 8781

eureka:
  client:
    service-url:
      defautZone: http://localhost:8761/eureka

feign:
  hystrix:
    enabled: true

management:
  endpoint:
    web:
      exposure:
        include: "*"




#server.port = 8781
#spring.application.name=produit-service
#spring.datasource.url = jdbc:h2:mem:produit-db
#spring.cloud.discovery.enabled=true

#actuator
#management.endpoints.web.exposure.include=*
